# Generated by Django 5.0.1 on 2024-01-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('referencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
