# Generated by Django 5.0.1 on 2024-01-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste', '0002_itempedido_pedido_model_itempedido_pedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido_Model',
            new_name='PedidoModel',
        ),
    ]
