# Generated by Django 5.0.1 on 2024-01-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste', '0003_rename_pedido_model_pedidomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomodel',
            name='itens_pedido',
            field=models.ManyToManyField(blank=True, null=True, to='app_teste.itempedido'),
        ),
    ]
