# Generated by Django 5.0.1 on 2024-02-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste', '0004_alter_pedidomodel_itens_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomodel',
            name='data_de_locacao',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
