# Generated by Django 5.0.1 on 2024-02-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste', '0005_pedidomodel_data_de_locacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomodel',
            name='local',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='observacao',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
