# Generated by Django 5.0.1 on 2024-10-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste', '0006_pedidomodel_local_pedidomodel_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidomodel',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='nome',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='telefone',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pedidomodel',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
