# Generated by Django 5.0.1 on 2024-10-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste', '0007_remove_pedidomodel_cliente_pedidomodel_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomodel',
            name='nome',
            field=models.CharField(max_length=80),
        ),
    ]
