# Generated by Django 5.0.1 on 2024-10-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste', '0008_alter_pedidomodel_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomodel',
            name='observacao',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
