# Generated by Django 5.0.1 on 2024-10-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste', '0009_alter_pedidomodel_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomodel',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedidomodel',
            name='local',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedidomodel',
            name='observacao',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='pedidomodel',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
